### ISSUE TITLE
Does not work in mobile browsers

### ISSUE THREAD

**Issue by jroets** [tbosch/jasmine-ui#22]
Using jstestdriver, attempting to run a test using a mobile browser in Android of iOS, the jasmine-ui tests always require human intervention, because even though pop-ups can be allowed on mobile browsers through "Settings" on the device, the browsers always ask for the user's permission (through a dialog box) before allowing any popped window, which means automation is not possible.

And, if I actually do give permission for the popped window, errors are thrown and reported by jstestdriver, both in Mobile Safari, the Android browser, and the mobile Chrome browser. 

I can give details of errors if desired; but I figured that perhaps mobile browsers were not considered; and so perhaps this is a feature request.

**Comment by tbosch** [comment]
Thanks for submitting this. I will look into this soon. Our goal is explicitly to support mobile browsers!
I will double check this behaviour that the device is prompting for every popup...

Besides that, the errors in js-test-driver should not happen. Could you provide our js-test-driver config file?

Which version of jasmine-ui are you using?

Tobias

**Comment by tbosch** [comment]
My new project uitest.js does no more use a popup but an iframe, and has been tested on Android 2.3+ and iOS. It also copies the `<meta>` tag from the iframe to the container so that the scaling of the viewport is ok and you get kind of a layout preview.

Jasmine-Ui has been superseded by uitest.js:
- Github: [https://github.com/tigbro/uitest.js](https://github.com/tigbro/uitest.js)
- Migration-Guide and why: [https://github.com/tigbro/uitest.js/blob/master/docs/jasmineUiMigration.md](https://github.com/tigbro/uitest.js/blob/master/docs/jasmineUiMigration.md).

Closing this as this project is no more active...
